### ISSUE TITLE
LLD usage

### ISSUE THREAD

**Issue by pravic** [nnethercote/perf-book#34]
[Compile times - Linking](https://nnethercote.github.io/perf-book/compile-times.html#linking) suggests to use `lld` via a `RUSTFLAGS="-C link-arg=-fuse-ld=lld"` flag. However, an easier way to do it (at least on Windows) is the [`linker` parameter](https://doc.rust-lang.org/nightly/cargo/reference/config.html#targettriplelinker) in cargo config:

```toml
[target.x86_64-pc-windows-msvc]
linker = "rust-lld"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld"]
```
