### ISSUE TITLE
Different linker project-wise

### ISSUE THREAD

**Issue by frederikhors** [nnethercote/perf-book#79]
In the [linker section](https://nnethercote.github.io/perf-book/build-configuration.html#linking) you're not mentioning the way of using a different linker project-wise:

From: https://github.com/rust-lang/rust/issues/71520#issuecomment-2007146769:

> Create a config.toml file in your project directory.
> In the file put linker = "rust-lld" under your target.

> In case of Windows it's:

```toml
[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
```

What do you think?
